# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-19 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=11)),
                ('loginname', models.CharField(max_length=30)),
                ('pwd', models.CharField(max_length=20)),
                ('uemail', models.EmailField(max_length=30)),
                ('url', models.URLField()),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
    ]
