# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-20 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190919_0637'),
    ]

    operations = [
        migrations.CreateModel(
            name='information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20)),
                ('time', models.DateField()),
                ('about', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'message',
            },
        ),
    ]
