# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-20 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190920_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='reason',
            field=models.CharField(default='不为啥', max_length=20),
        ),
    ]
