# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-20 05:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190920_0457'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='information',
            new_name='Message',
        ),
    ]
