# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-21 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190920_0505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justOne', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=50)),
                ('select', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=1000)),
                ('imgs', models.ImageField(null=True, upload_to='static/upload')),
            ],
            options={
                'db_table': 'imgs',
            },
        ),
    ]
