# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-22 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190921_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='imgs',
            field=models.CharField(default=True, max_length=40),
        ),
    ]
