# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-23 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_message_imgs'),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutMy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'about',
            },
        ),
    ]
