# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-23 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_aboutmy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutmy',
            old_name='message',
            new_name='text',
        ),
    ]
